spring.application.name=splitease

#spring.datasource.url=jdbc:postgresql://localhost:5432/splitease
#spring.datasource.username=postgres
#spring.datasource.password=0000

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update

jwt.secret=SJ2vfii4hxjSS3OxfwGfrxBmoi3Ji7h5djtSKw+Au6Q=

