spring.application.name=splitease

spring.datasource.url=jdbc:postgresql://localhost:5432/splitease
spring.datasource.username=postgres
spring.datasource.password=0000

#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
#
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
server.port=${PORT:8080}

